// SET TO 'true' IN .env TO SHOW THE MAINTENANCE PAGE IN PRODUCTION
// SET TO 'false' IN .env TO CONTINUE DEVELOPMENT OF THE FULL SITE
export const IS_MAINTENANCE_MODE = process.env.NEXT_PUBLIC_MAINTENANCE_MODE === 'true';
